"""initial schema

Revision ID: 0001_initial
Revises: 
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_phone'), ['phone'], unique=False)

    op.create_table('otp_request_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_request_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_request_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_request_log_ip'), ['ip'], unique=False)
        batch_op.create_index('ix_otp_request_log_phone_created', ['phone', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_key', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('issues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reporter_id', sa.String(length=32), nullable=False),
    sa.Column('client_report_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('pothole_road', 'garbage', 'footpath', 'streetlight', 'water_drainage', 'manhole', 'traffic_infrastructure', 'fallen_tree', 'public_property', 'other', name='category', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('reported', 'community_verified', 'submitted_to_authority', 'authority_acknowledged', 'in_progress', 'resolution_claimed', 'resolved', 'reopened', 'duplicate', 'removed', name='status', native_enum=False, length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('locality', sa.String(length=120), nullable=True),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'client_report_id', name='uq_issues_reporter_client_report')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_issues_lat_lng', ['latitude', 'longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Enum('confirmation_received', 'status_changed', name='activitytype', native_enum=False, length=32), nullable=False),
    sa.Column('from_status', sa.Enum('reported', 'community_verified', 'submitted_to_authority', 'authority_acknowledged', 'in_progress', 'resolution_claimed', 'resolved', 'reopened', 'duplicate', 'removed', name='status', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('reported', 'community_verified', 'submitted_to_authority', 'authority_acknowledged', 'in_progress', 'resolution_claimed', 'resolved', 'reopened', 'duplicate', 'removed', name='status', native_enum=False, length=32), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_activity_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('confirmations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id', 'user_id', name='uq_confirmations_issue_user')
    )
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmations_issue_id'), ['issue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_confirmations_user_id'), ['user_id'], unique=False)

    op.create_table('issue_photos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('issue_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('original_key', sa.String(length=400), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_photos_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_photos_issue_id'))

    op.drop_table('issue_photos')
    with op.batch_alter_table('confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confirmations_user_id'))
        batch_op.drop_index(batch_op.f('ix_confirmations_issue_id'))

    op.drop_table('confirmations')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_user_created')
        batch_op.drop_index(batch_op.f('ix_activity_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_issue_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_created_at'))

    op.drop_table('activity_events')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_reporter_id'))
        batch_op.drop_index('ix_issues_lat_lng')
        batch_op.drop_index(batch_op.f('ix_issues_created_at'))

    op.drop_table('issues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('otp_request_log', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_request_log_phone_created')
        batch_op.drop_index(batch_op.f('ix_otp_request_log_ip'))
        batch_op.drop_index(batch_op.f('ix_otp_request_log_created_at'))

    op.drop_table('otp_request_log')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_phone'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_created_at'))

    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
